### ISSUE TITLE
When baking hsphysics via baked pdf cli, validation process fails 

### ISSUE THREAD

**Issue by omehes** [openstax/cnx-recipes#1580]
Run the baked pdf cli commands:
1. docker-compose run --rm fetch-book (--with-resources) hsphysics
2. docker-compose run --rm assemble-book hsphysics
3. docker-compose run --rm bake-book hsphysics

Result: when baking process comes to its validation phase, the following error is shown:

```==> Validating ./data/hsphysics/collection.baked.xhtml
Traceback (most recent call last):
  File "/code/venv/bin/cnx-epub-validate-collated", line 10, in <module>
    sys.exit(main())
  File "/code/venv/lib/python3.6/site-packages/cnxepub/scripts/collated_single_html/main.py", line 49, in main
    binder = reconstitute(args.collated_html)
  File "/code/venv/lib/python3.6/site-packages/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File "/code/venv/lib/python3.6/site-packages/cnxepub/adapters.py", line 359, in adapt_single_html
    _adapt_single_html_tree(binder, body[0], nav_tree, top_metadata=metadata)
  File "/code/venv/lib/python3.6/site-packages/cnxepub/adapters.py", line 514, in _adapt_single_html_tree
    id_map=id_map, depth=depth+1)
  File "/code/venv/lib/python3.6/site-packages/cnxepub/adapters.py", line 472, in _adapt_single_html_tree
    child.xpath('./*[@data-type="metadata"]')[0])
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 74, in parse_metadata
    return parser()
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 108, in __call__
    return self.metadata
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 128, in metadata
    "A value for '{}' could not be found.".format(key))
ValueError: A value for 'title' could not be found.
/code/script/bake-book: ERROR: could not run [cnx-epub-validate-collated ./data/hsphysics/collection.baked.xhtml]```

...baked.xhtml file is created in the book's folder

**Comment by wilkus27** [comment]
Problem occurs because in EOC are created two composite chapters:

![image](https://user-images.githubusercontent.com/40228854/71262195-728d5c00-233f-11ea-87a2-7202efe0efbe.png)

https://github.com/openstax/cnx-recipes/blob/master/recipes/books/hs-physics/_config.scss

But value of `$Config_hasCompositeChapter` is set to false.

![image](https://user-images.githubusercontent.com/40228854/71262257-90f35780-233f-11ea-895b-07b5f7350ec1.png)

It will be resolved by https://github.com/openstax/cnx-recipes/pull/1707
