### ISSUE TITLE
World History Ch 10 -- TOC hierarchy incorrect -- EOC hierarchy incorrect

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4827]
![image](https://user-images.githubusercontent.com/89537088/184748252-508495c1-586e-4477-9992-693235fe796d.png)

![image](https://user-images.githubusercontent.com/89537088/184747615-fd163d56-c869-4e2a-a128-283f078fa482.png)

# Brief Description of Scenario

Possibly related to [https://github.com/openstax/cnx-recipes/issues/4280](url)
**TOC:**
“Key Terms” and “Section Summary” should NOT be indented and should NOT appear under “Assessments” heading.
“Assessments” heading should precede “Review Questions”.
**EOC:**
“Assessments” heading should NOT appear directly above “Review Questions”.
“Assessments” heading should appear directly above “Review Questions”.

# Pattern of Occurrence 
This is the test chapter, so this is the first occurrence.

# Acceptance Criteria
**For TOC:**
“Key Terms” and “Section Summary” will NOT be indented and will NOT appear under “Assessments” heading.
“Assessments” heading will precede “Review Questions”.
**For EOC:**
“Assessments” heading will NOT appear directly above “Review Questions” 
“Assessments” heading will appear directly above “Review Questions”.

# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** Ch 10 TOC  Ch 10 EOC
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax This book's TOC was created with having Units in the structure. Once Units are added all of the EOC items won't appear in the TOC and  only the Assessment header. 

Here is a sample screenshot from the prototype chapter. 
![image](https://user-images.githubusercontent.com/11299125/184934448-3222a063-abda-4cc6-aa33-57086745aa4a.png)

**Comment by wilkus27** [comment]
@lwtchu There are some problems with baking. It fails on git-matify step:

```
==> Starting: git-mathify
08:03:16.805Z FATAL node-typeset:
  Failed to launch the browser process!
  [0831/080316.781406:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
  
  
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
  
  --
  Error: Failed to launch the browser process!
  [0831/080316.781406:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
  
  
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
  
      at onClose (/workspace/enki/mathify/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
      at ChildProcess.<anonymous> (/workspace/enki/mathify/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:79)
      at ChildProcess.emit (events.js:327:22)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
/dockerfiles/docker-entrypoint.sh: ERROR: could not run [node /workspace/enki/mathify/typeset/start.js -i /data/linked-single/world-history.linked.xhtml -o /data/mathified-single/world-history.mathified.xhtml -f svg]
```

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-31 18-07-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2dadd83d-7661-4e17-ad2e-1a601d1aeb8b)

![Screenshot from 2022-08-31 18-07-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/62c6c236-84c6-4683-a02b-f6146ac07bf2)

**Comment by lwtchu** [comment]
![Screen Shot 2022-09-13 at 12 42 59 PM](https://user-images.githubusercontent.com/11299125/189973209-092a4c44-f78e-4fd7-a1c0-c94c4aa7b1e8.png)
book generated again so tested and closed
