### ISSUE TITLE
cookbook error message improvement - empty subcollection error

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5100]
# Brief Description of Scenario
there was an accidental empty subcollection placed in a collection (college-success) while trying to generate another book (college-success-high-school) in the same bundle.

# Acceptance Criteria
- error should specifically say something about an issue with the Collection structure of (enter specific book). example: Something is missing for [slug] collection! Please check if element related with [name] direction is properly formatted or tagged.
  
# Location(s) 
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle/tree/40c68ca484247d6087d96105cdc7ef6541ad1498
- **collection slug:** college-success-high-school

please use that commit to test

# Error message
```
Error:
 + [[ -n git-bake ]]
 + [[ -d common-log ]]
 + [[ -d book ]]
 + [[ -n 20230410.201926 ]]
 + export ARG_S3_BUCKET_NAME=
 + ARG_S3_BUCKET_NAME=
 + TRACE_ON=1
 + docker-entrypoint.sh git-bake
 + export 'PS4=+ [${BASH_SOURCE##*/}:${LINENO}] '
 + PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
 + [docker-entrypoint.sh:13] c_red=
 + [docker-entrypoint.sh:14] c_green=
 + [docker-entrypoint.sh:15] c_yellow=
 + [docker-entrypoint.sh:16] c_blue=
 + [docker-entrypoint.sh:17] c_purple=
 + [docker-entrypoint.sh:18] c_cyan=
 + [docker-entrypoint.sh:19] c_none=
 ++ [docker-entrypoint.sh:20] tput colors
 tput: No value for $TERM and no -T specified
 + [docker-entrypoint.sh:20] [[ '' -ge 8 ]]
 + [docker-entrypoint.sh:43] [[ -n /workspace/enki ]]
 + [docker-entrypoint.sh:45] STEP_CONFIG_FILE=/workspace/enki/step-config.json
 + [docker-entrypoint.sh:46] DOCKERFILES_ROOT=/dockerfiles
 + [docker-entrypoint.sh:47] BAKERY_SCRIPTS_ROOT=/workspace/enki/bakery-src
 + [docker-entrypoint.sh:48] PYTHON_VENV_ROOT=/workspace/enki/venv
 + [docker-entrypoint.sh:49] COOKBOOK_ROOT=/workspace/enki/cookbook
 + [docker-entrypoint.sh:50] MATHIFY_ROOT=/workspace/enki/mathify
 + [docker-entrypoint.sh:51] JS_UTILS_STUFF_ROOT=/workspace/enki/bakery-js
 + [docker-entrypoint.sh:52] BOOK_STYLES_ROOT=/workspace/enki/ce-styles/styles/output
 + [docker-entrypoint.sh:53] XHTML_VALIDATOR_ROOT=/workspace/enki/xhtml-validator/build/libs
 + [docker-entrypoint.sh:54] START_AT_STEP=
 + [docker-entrypoint.sh:55] STOP_AT_STEP=
 + [docker-entrypoint.sh:56] KCOV_DIR=
 + [docker-entrypoint.sh:57] LOCAL_ATTIC_DIR=
 + [docker-entrypoint.sh:59] source /workspace/enki/venv/bin/activate
 ++ [activate:38] deactivate nondestructive
 ++ [activate:6] '[' -n '' ']'
 ++ [activate:11] '[' -n '' ']'
 ++ [activate:20] '[' -n /usr/bin/bash -o -n '' ']'
 ++ [activate:21] hash -r
 ++ [activate:24] '[' -n '' ']'
 ++ [activate:30] unset VIRTUAL_ENV
 ++ [activate:31] '[' '!' nondestructive = nondestructive ']'
 ++ [activate:40] VIRTUAL_ENV=/workspace/enki/venv
 ++ [activate:41] export VIRTUAL_ENV
 ++ [activate:43] _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/rubies/ruby-2.6.6/bin/:/root/.nvm/versions/node/v18.14.2/bin/:/workspace/enki/nvm/versions/node/v18.14.2/bin/:/dockerfiles/
 ++ [activate:44] PATH=/workspace/enki/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/rubies/ruby-2.6.6/bin/:/root/.nvm/versions/node/v18.14.2/bin/:/workspace/enki/nvm/versions/node/v18.14.2/bin/:/dockerfiles/
 ++ [activate:45] export PATH
 ++ [activate:50] '[' -n '' ']'
 ++ [activate:55] '[' -z '' ']'
 ++ [activate:56] _OLD_VIRTUAL_PS1=
 ++ [activate:57] '[' 'x(venv) ' '!=' x ']'
 ++ [activate:58] PS1='(venv) '
 ++ [activate:68] export PS1
 ++ [activate:74] '[' -n /usr/bin/bash -o -n '' ']'
 ++ [activate:75] hash -r
 + [docker-entrypoint.sh:364] first_arg=git-bake
 ++ [docker-entrypoint.sh:365] jq -r '.pipelines."git-bake"|@sh'
 + [docker-entrypoint.sh:365] pipeline_steps=null
 + [docker-entrypoint.sh:367] [[ git-bake == local-create-book-directory ]]
 + [docker-entrypoint.sh:369] [[ null = \n\u\l\l ]]
 ++ [docker-entrypoint.sh:370] echo git-bake
 ++ [docker-entrypoint.sh:370] tr -d \'
 + [docker-entrypoint.sh:370] do_step_named git-bake
 + [docker-entrypoint.sh:264] step_name=git-bake
 + [docker-entrypoint.sh:265] [[ '' == git-bake ]]
 + [docker-entrypoint.sh:267] [[ -n '' ]]
 + [docker-entrypoint.sh:270] [[ '' == git-bake ]]
 + [docker-entrypoint.sh:277] [[ ! -n '' ]]
 + [docker-entrypoint.sh:278] [[ -n '' ]]
 + [docker-entrypoint.sh:279] say '==> Starting: git-bake'
 + [docker-entrypoint.sh:33] echo -e '==> Starting: git-bake'
 ==> Starting: git-bake
 + [docker-entrypoint.sh:280] do_step git-bake
 + [docker-entrypoint.sh:153] step_name=git-bake
 + [docker-entrypoint.sh:156] shift 1
 + [docker-entrypoint.sh:158] '[' -n '' ']'
 + [docker-entrypoint.sh:173] case $step_name in
 ++ [docker-entrypoint.sh:234] jq -r '.steps."git-bake"|not|not'
 + [docker-entrypoint.sh:234] step_entry=true
 + [docker-entrypoint.sh:236] [[ true == \f\a\l\s\e ]]
 ++ [docker-entrypoint.sh:239] jq -r '.steps."git-bake".inputDirs|@sh'
 + [docker-entrypoint.sh:239] input_dirs=''\''IO_BOOK'\'' '\''IO_FETCHED'\'' '\''IO_ASSEMBLED'\'''
 ++ [docker-entrypoint.sh:240] jq -r '.steps."git-bake".outputDirs|@sh'
 + [docker-entrypoint.sh:240] output_dirs=''\''IO_BAKED'\'''
 ++ [docker-entrypoint.sh:241] jq -r '.steps."git-bake".requiredEnv|@sh'
 + [docker-entrypoint.sh:241] required_envs=
 + [docker-entrypoint.sh:246] for input_dir in $input_dirs
 ++ [docker-entrypoint.sh:247] echo ''\''IO_BOOK'\'''
 ++ [docker-entrypoint.sh:247] tr -d \'
 + [docker-entrypoint.sh:247] check_input_dir IO_BOOK
 + [docker-entrypoint.sh:73] [[ -n IO_BOOK ]]
 + [docker-entrypoint.sh:74] pointer=IO_BOOK
 + [docker-entrypoint.sh:75] dir_name=book
 + [docker-entrypoint.sh:76] [[ -n book ]]
 + [docker-entrypoint.sh:77] [[ -d book ]]
 + [docker-entrypoint.sh:246] for input_dir in $input_dirs
 ++ [docker-entrypoint.sh:247] tr -d \'
 ++ [docker-entrypoint.sh:247] echo ''\''IO_FETCHED'\'''
 + [docker-entrypoint.sh:247] check_input_dir IO_FETCHED
 + [docker-entrypoint.sh:73] [[ -n IO_FETCHED ]]
 + [docker-entrypoint.sh:74] pointer=IO_FETCHED
 + [docker-entrypoint.sh:75] dir_name=fetched
 + [docker-entrypoint.sh:76] [[ -n fetched ]]
 + [docker-entrypoint.sh:77] [[ -d fetched ]]
 + [docker-entrypoint.sh:246] for input_dir in $input_dirs
 ++ [docker-entrypoint.sh:247] tr -d \'
 ++ [docker-entrypoint.sh:247] echo ''\''IO_ASSEMBLED'\'''
 + [docker-entrypoint.sh:247] check_input_dir IO_ASSEMBLED
 + [docker-entrypoint.sh:73] [[ -n IO_ASSEMBLED ]]
 + [docker-entrypoint.sh:74] pointer=IO_ASSEMBLED
 + [docker-entrypoint.sh:75] dir_name=assembled
 + [docker-entrypoint.sh:76] [[ -n assembled ]]
 + [docker-entrypoint.sh:77] [[ -d assembled ]]
 + [docker-entrypoint.sh:249] for output_dir in $output_dirs
 ++ [docker-entrypoint.sh:250] tr -d \'
 ++ [docker-entrypoint.sh:250] echo ''\''IO_BAKED'\'''
 + [docker-entrypoint.sh:250] check_output_dir IO_BAKED
 + [docker-entrypoint.sh:80] [[ -n IO_BAKED ]]
 + [docker-entrypoint.sh:81] pointer=IO_BAKED
 + [docker-entrypoint.sh:82] dir_name=baked
 + [docker-entrypoint.sh:83] [[ -n baked ]]
 + [docker-entrypoint.sh:85] [[ baked =~ /data/ ]]
 + [docker-entrypoint.sh:88] [[ -d baked ]]
 + [docker-entrypoint.sh:254] step_file=/dockerfiles/steps/git-bake.bash
 + [docker-entrypoint.sh:256] [[ -f /dockerfiles/steps/git-bake.bash ]]
 + [docker-entrypoint.sh:257] source /dockerfiles/steps/git-bake.bash
 ++ [git-bake.bash:1] parse_book_dir
 ++ [docker-entrypoint.sh:126] check_input_dir IO_BOOK
 ++ [docker-entrypoint.sh:73] [[ -n IO_BOOK ]]
 ++ [docker-entrypoint.sh:74] pointer=IO_BOOK
 ++ [docker-entrypoint.sh:75] dir_name=book
 ++ [docker-entrypoint.sh:76] [[ -n book ]]
 ++ [docker-entrypoint.sh:77] [[ -d book ]]
 ++ [docker-entrypoint.sh:128] [[ -f book/pdf_filename ]]
 +++ [docker-entrypoint.sh:128] cat book/pdf_filename
 ++ [docker-entrypoint.sh:128] ARG_TARGET_PDF_FILENAME=college-success-high-school-40c68ca484247d6087d96105cdc7ef6541ad1498-git-4206.pdf
 ++ [docker-entrypoint.sh:129] [[ -f book/collection_id ]]
 ++ [docker-entrypoint.sh:130] [[ -f book/server ]]
 ++ [docker-entrypoint.sh:131] [[ -f book/server_shortname ]]
 +++ [docker-entrypoint.sh:132] cat book/version
 ++ [docker-entrypoint.sh:132] ARG_COLLECTION_VERSION=40c68ca484247d6087d96105cdc7ef6541ad1498
 ++ [docker-entrypoint.sh:134] [[ -f book/repo ]]
 +++ [docker-entrypoint.sh:134] cat book/repo
 ++ [docker-entrypoint.sh:134] ARG_REPO_NAME=openstax/osbooks-college-success-bundle
 ++ [docker-entrypoint.sh:135] [[ -f book/slug ]]
 +++ [docker-entrypoint.sh:135] cat book/slug
 ++ [docker-entrypoint.sh:135] ARG_TARGET_SLUG_NAME=college-success-high-school
 +++ [docker-entrypoint.sh:136] cat book/version
 ++ [docker-entrypoint.sh:136] ARG_GIT_REF=40c68ca484247d6087d96105cdc7ef6541ad1498
 ++ [git-bake.bash:3] shopt -s globstar nullglob
 ++ [git-bake.bash:4] for collection in "$IO_ASSEMBLED/"*.assembled.xhtml
 +++ [git-bake.bash:5] awk '-F[.]' '{ print $1; }'
 +++ [git-bake.bash:5] basename assembled/college-success-concise.assembled.xhtml
 ++ [git-bake.bash:5] slug_name=college-success-concise
 +++ [git-bake.bash:8] read_style college-success-concise
 +++ [docker-entrypoint.sh:120] slug_name=college-success-concise
 ++++ [docker-entrypoint.sh:121] xmlstarlet sel -t --match '//*[@style][@slug="college-success-concise"]' --value-of @style
 +++ [docker-entrypoint.sh:121] style_name=college-success
 +++ [docker-entrypoint.sh:122] echo college-success
 ++ [git-bake.bash:8] style_name=college-success
 ++ [git-bake.bash:9] style_file=/workspace/enki/ce-styles/styles/output/college-success-pdf.css
 ++ [git-bake.bash:11] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:13] cp /workspace/enki/ce-styles/styles/output/college-success-pdf.css baked/the-style-pdf.css
 ++ [git-bake.bash:19] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:21] export VERBOSE=1
 ++ [git-bake.bash:21] VERBOSE=1
 ++ [git-bake.bash:22] /workspace/enki/cookbook/bake -b college-success -i assembled/college-success-concise.assembled.xhtml -o baked/college-success-concise.baked.xhtml
 Open: 1.6888e-05 s
 Parse: 0.010606319 s
 Bake: 0.770413521 s
 Write: 0.01224807 s
 ++ [git-bake.bash:23] sed -i 's%<\/head>%<link rel="stylesheet" type="text/css" href="the-style-pdf.css" />&%' baked/college-success-concise.baked.xhtml
 ++ [git-bake.bash:4] for collection in "$IO_ASSEMBLED/"*.assembled.xhtml
 +++ [git-bake.bash:5] awk '-F[.]' '{ print $1; }'
 +++ [git-bake.bash:5] basename assembled/college-success-high-school.assembled.xhtml
 ++ [git-bake.bash:5] slug_name=college-success-high-school
 +++ [git-bake.bash:8] read_style college-success-high-school
 +++ [docker-entrypoint.sh:120] slug_name=college-success-high-school
 ++++ [docker-entrypoint.sh:121] xmlstarlet sel -t --match '//*[@style][@slug="college-success-high-school"]' --value-of @style
 +++ [docker-entrypoint.sh:121] style_name=college-success
 +++ [docker-entrypoint.sh:122] echo college-success
 ++ [git-bake.bash:8] style_name=college-success
 ++ [git-bake.bash:9] style_file=/workspace/enki/ce-styles/styles/output/college-success-pdf.css
 ++ [git-bake.bash:11] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:13] cp /workspace/enki/ce-styles/styles/output/college-success-pdf.css baked/the-style-pdf.css
 ++ [git-bake.bash:19] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:21] export VERBOSE=1
 ++ [git-bake.bash:21] VERBOSE=1
 ++ [git-bake.bash:22] /workspace/enki/cookbook/bake -b college-success -i assembled/college-success-high-school.assembled.xhtml -o baked/college-success-high-school.baked.xhtml
 Open: 1.8604e-05 s
 Parse: 0.010662427 s
 Bake: 0.765924287 s
 Write: 0.010240503 s
 ++ [git-bake.bash:23] sed -i 's%<\/head>%<link rel="stylesheet" type="text/css" href="the-style-pdf.css" />&%' baked/college-success-high-school.baked.xhtml
 ++ [git-bake.bash:4] for collection in "$IO_ASSEMBLED/"*.assembled.xhtml
 +++ [git-bake.bash:5] awk '-F[.]' '{ print $1; }'
 +++ [git-bake.bash:5] basename assembled/college-success.assembled.xhtml
 ++ [git-bake.bash:5] slug_name=college-success
 +++ [git-bake.bash:8] read_style college-success
 +++ [docker-entrypoint.sh:120] slug_name=college-success
 ++++ [docker-entrypoint.sh:121] xmlstarlet sel -t --match '//*[@style][@slug="college-success"]' --value-of @style
 +++ [docker-entrypoint.sh:121] style_name=college-success
 +++ [docker-entrypoint.sh:122] echo college-success
 ++ [git-bake.bash:8] style_name=college-success
 ++ [git-bake.bash:9] style_file=/workspace/enki/ce-styles/styles/output/college-success-pdf.css
 ++ [git-bake.bash:11] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:13] cp /workspace/enki/ce-styles/styles/output/college-success-pdf.css baked/the-style-pdf.css
 ++ [git-bake.bash:19] [[ -f /workspace/enki/ce-styles/styles/output/college-success-pdf.css ]]
 ++ [git-bake.bash:21] export VERBOSE=1
 ++ [git-bake.bash:21] VERBOSE=1
 ++ [git-bake.bash:22] /workspace/enki/cookbook/bake -b college-success -i assembled/college-success.assembled.xhtml -o baked/college-success.baked.xhtml
 The recipe has an error: undefined method `target_label' for nil:NilClass
 at or near the following highlighted line
 -----+ /workspace/enki/cookbook/lib/recipes/college-success/bake -----
 16| BakePreface.v1(book: book)
 17| BakeChapterTitle.v1(book: book)
 18| BakeChapterIntroductions.v1(book: book)
 19|
 20| BakeAutotitledNotes.v1(
 Encountered on line 4 in the input document on element:
 <span xmlns="http://www.w3.org/1999/xhtml" data-type="" itemprop="" class="os-text">...</span>
 Full backtrace:
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/v2.rb:12:in `block in bake'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:127:in `yield'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:127:in `block (3 levels) in build_within_other_enumerator'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:113:in `yield'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:113:in `block (2 levels) in build_within_element'
 /usr/local/rvm/gems/ruby-2.6.6/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
 /usr/local/rvm/gems/ruby-2.6.6/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
 /usr/local/rvm/gems/ruby-2.6.6/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:90:in `block in build_within_element'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:126:in `each'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:126:in `each'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:126:in `block (2 levels) in build_within_other_enumerator'
 /workspace/enki/cookbook/lib/kitchen/element_base.rb:848:in `yield'
 /workspace/enki/cookbook/lib/kitchen/element_base.rb:848:in `block in as_enumerator'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:123:in `each'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:123:in `each'
 /workspace/enki/cookbook/lib/kitchen/element_enumerator_factory.rb:123:in `block in build_within_other_enumerator'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/v2.rb:6:in `each'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/v2.rb:6:in `each'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/v2.rb:6:in `bake'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/main.rb:27:in `v2'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/v1.rb:6:in `bake'
 /workspace/enki/cookbook/lib/kitchen/directions/bake_chapter_introductions/main.rb:7:in `v1'
 /workspace/enki/cookbook/lib/recipes/college-success/bake:18:in `block in <main>'
 /workspace/enki/cookbook/lib/kitchen/recipe.rb:59:in `block in bake'
 /workspace/enki/cookbook/lib/kitchen/recipe.rb:98:in `with_my_locales'
 /workspace/enki/cookbook/lib/kitchen/recipe.rb:58:in `bake'
 /workspace/enki/cookbook/lib/kitchen/oven.rb:35:in `block in bake'
 /workspace/enki/cookbook/lib/kitchen/oven.rb:33:in `each'
 /workspace/enki/cookbook/lib/kitchen/oven.rb:33:in `bake'
 /workspace/enki/cookbook/lib/recipes/college-success/bake:97:in `<main>'
```

**Comment by Stackblocks** [comment]
New error showing up correctly when I bake with content from `osbooks-college-success-bundle` on `40c68ca484247d6087d96105cdc7ef6541ad1498`

![CleanShot 2023-04-27 at 11.31.16@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bdeb90ba-b9cc-4ac5-b351-65e5ac3954e1)
