### ISSUE TITLE
Cannot Bake Algebra & Trigonometry

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#982]
# What happened?
Multiple devs and testers cannot bake _Algebra & Trigonometry_ on Katalyst01.  

# Environment:

- **Book(s)**: _Algebra & Trigonometry_
- **URL/Server**: https://katalyst01.cnx.org/contents/E6wQevFf:nU8Qkzwo
- **Location (page number, chapter/section)**: N/A
- **Suggested nearby searchable text**: N/A
- **Browser**: multiple

# Screenshot
Screenshot of logs, provided by Natalia, from katalyst01.cnx.org.  No errors can be seen:
![image (3)](https://user-images.githubusercontent.com/7863733/55248015-f2562200-5216-11e9-80ec-a32ed94edcd3.png)

# Additional notes
Notes from @wilkus27:
Ok, so I tried to bake it from `precalculus-recipe-632` branch and from `905-section-exercises` and it doesn't work. There is no information on page with content-status that baking process start. There is no problem with other books. Baking process is working for them properly.
I noticed that Algebra and Trygonometry was baking last time 03-22 and the process failure.

**Comment by helenemccarron** [comment]
I think we need someone from CNX to take a look at the queue on the server, injecting the recipe doesn't start the baking process.

**Comment by brittweinstein** [comment]
Sent to CNX!

**Comment by karenc** [comment]
"Algebra and Trigonometry" on katalyst01 is in the "processing" state:

```
repository=> select * from modulestates;
 stateid |    statename
---------+------------------
       0 | unknown
       1 | current
       4 | obsolete
       5 | post-publication
       6 | processing
       7 | errored
       8 | fallback
(7 rows)

repository=> select stateid from modules where ident_hash(uuid, major_version, minor_version) = '13ac107a-f15f-49d2-97e8-60ab2e3b519c@11.1';
 stateid
---------
       6
(1 row)
```

I manually set the state to "post-publishing" so the book can be added to the
baking queue:

```
repository=> update modules set stateid = 5 where ident_hash(uuid, major_version, minor_version) = '13ac107a-f15f-49d2-97e8-60ab2e3b519c@11.1';                               UPDATE 1

repository=> select stateid from modules where ident_hash(uuid, major_version, minor_version) = '13ac107a-f15f-49d2-97e8-60ab2e3b519c@11.1';
 stateid
---------
       6
(1 row)
```

The book is stuck in the "processing" state and appears on the Content Status page as "queued".

Rabbitmq says there's nothing in the queues:

```
administrator@katalyst01:~$ sudo rabbitmqctl list_queues -p /publishing name messages consumers
Listing queues ...
celery@katalyst01.celery.pidbox 0       1
celeryev.5f19f2d0-5385-4667-ac87-723d27fbb47b   0       1
default 0       1
deferred        0       1
```

Looking at the publishing celery worker logs:

```
2019-03-29 19:31:29,505 DEBUG [cnxpublishing][MainThread] More recent version (module_ident=661421 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@3.8) in queue. Move this message (module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1) to the deferred (low priority) queue
2019-03-29 19:34:30,215 DEBUG [cnxpublishing][MainThread] Starting baking module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1
2019-03-29 19:34:30,255 DEBUG [cnxpublishing][MainThread] Finished unbaking module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1 with a final state of 'current'.
```

```
[2019-03-29 19:31:29,071: CRITICAL/MainProcess] Couldn't ack 1, reason:RecoverableConnectionError(None, u'connection already closed', None, u'')
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/kombu/message.py", line 130, in ack_log_error
    self.ack(multiple=multiple)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/amqp/channel.py", line 1392, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 47, in send_method
    raise RecoverableConnectionError('connection already closed')
RecoverableConnectionError: connection already closed
```

The latest logs are from 2019-03-29 19:34 UTC.  There are no newer logs.

**Comment by karenc** [comment]
Just when I thought nothing is happening, baking started suddenly:

```
==> /var/log/supervisor/publishing_celery_worker0-stdout---supervisor-dBK350.log <==
2019-03-29 19:31:29,347 DEBUG [cnxpublishing][MainThread] Finished unbaking module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1 with a final state of 'current'.
2019-03-29 19:31:29,505 DEBUG [cnxpublishing][MainThread] More recent version (module_ident=661421 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@3.8) in queue. Move this message (module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1) to the deferred (low priority) queue
2019-03-29 19:34:30,215 DEBUG [cnxpublishing][MainThread] Starting baking module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1
2019-03-29 19:34:30,255 DEBUG [cnxpublishing][MainThread] Finished unbaking module_ident=662617 ident_hash=8b89d172-2927-466f-8661-01abc7ccdba4@4.1 with a final state of 'current'.
2019-04-01 12:22:30,940 DEBUG [cnxpublishing][MainThread] Starting baking module_ident=530390 ident_hash=13ac107a-f15f-49d2-97e8-60ab2e3b519c@11.1
2019-04-01 12:22:30,958 DEBUG [cnxpublishing][MainThread] Starting baking module_ident=658895 ident_hash=9b08c294-057f-4201-9f48-5d6ad992740d@8.2
2019-04-01 12:22:31,144 DEBUG [cnxpublishing][MainThread] Starting baking module_ident=662616 ident_hash=fd53eae1-fa23-47c7-bb1b-972349835c3c@8.4
2019-04-01 12:24:53,798 DEBUG [cnxpublishing][MainThread] Exported module_ident=658895 ident_hash=9b08c294-057f-4201-9f48-5d6ad992740d@8.2
2019-04-01 12:25:58,310 DEBUG [cnxpublishing][MainThread] Exported module_ident=530390 ident_hash=13ac107a-f15f-49d2-97e8-60ab2e3b519c@11.1
2019-04-01 12:26:07,943 DEBUG [cnxpublishing][MainThread] Exported module_ident=662616 ident_hash=fd53eae1-fa23-47c7-bb1b-972349835c3c@8.4
```

**Comment by karenc** [comment]
According to the [Content Status page](https://katalyst01.cnx.org/a/content-status/13ac107a-f15f-49d2-97e8-60ab2e3b519c), "Algebra and Trigonometry" 11.1 finished baking successfully :tada:

I'm not sure if this fixes the original issue though.  I'm stopping my investigations for now until users report more problems.

**Comment by brittweinstein** [comment]
This issue seems to be resolved.
